name: Sanity Test with CML

on:
  pull_request:
    branches: [main]

jobs:
  cml-test:
    runs-on: ubuntu-latest
    container:
      image: docker://dvcorg/cml-py3:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        run: |
          pip install -r requirements.txt
          pip install pytest scikit-learn pandas

      - name: Run Pytest
        run: |
          if [ -f "data/iris.csv" ]; then
            pytest tests/test.py > report.txt
          else
            echo "Iris dataset not found. Skipping tests." > report.txt
          fi

      - name: Post CML Report
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cml comment report.txt

